# 🚀 Render Deployment Configuration for Chatty App

services:
  # 🖥️ Backend Service (Node.js API)
  - type: web
    name: chatty-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: chatty-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /api/auth/check
    
  # 🌐 Frontend Service (React App)
  - type: web
    name: chatty-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: https://chatty-backend.onrender.com
      - key: VITE_SOCKET_URL
        value: https://chatty-backend.onrender.com

# 🗄️ Database
databases:
  - name: chatty-mongodb
    databaseName: chatty
    user: chatty_user
    plan: free
